     * <p>
     * As with the try-with-resources statement, if multiple exceptions are thrown
     * the exception from the closure will be returned and the exception from closing
     * will be added as a suppressed exception.
        Throwable thrown = null;
            return action.call(self);
        } catch (Throwable e) {
            thrown = e;
            throw e;
            if (thrown != null) {
                Throwable suppressed = tryClose(self, true);
                if (suppressed != null) {
                    thrown.addSuppressed(suppressed);
                }
            } else {
                self.close();
            }
     * <p>
     * As with the try-with-resources statement, if multiple exceptions are thrown
     * the exception from the closure will be returned and the exception from closing
     * will be added as a suppressed exception.
        Throwable thrown = null;
            return action.call(self);
        } catch (Throwable e) {
            thrown = e;
            throw e;
            if (thrown != null) {
                Throwable suppressed = tryClose(self, true);
                if (suppressed != null) {
                    thrown.addSuppressed(suppressed);
                }
            } else {
                self.close();
            }
